export const PROJECTS_IMAGES = {
  "menu": [
    "/projects/menu/cart.png",
    "/projects/menu/categories.png",
    "/projects/menu/edit-category.png",
    "/projects/menu/edit-venue.png",
    "/projects/menu/home.png",
    "/projects/menu/item.png",
    "/projects/menu/menu.png",
    "/projects/menu/order.png",
    "/projects/menu/profile.png",
    "/projects/menu/public-menu.png",
    "/projects/menu/qr-code.png",
    "/projects/menu/signup.png",
    "/projects/menu/stats1.png",
    "/projects/menu/stats2.png",
    "/projects/menu/venues-empty.png",
    "/projects/menu/venues.png",
    "/projects/menu/verify.png",
    "/projects/menu/whatsapp.png"
  ],
  "jobsdublin": [
    "/projects/jobsdublin/created_company_page.png",
    "/projects/jobsdublin/create_vacancy.png",
    "/projects/jobsdublin/employers_vacancy_applications_page.png",
    "/projects/jobsdublin/employer_empty.png",
    "/projects/jobsdublin/employer_sign_up.png",
    "/projects/jobsdublin/employer_vacancy_list.png",
    "/projects/jobsdublin/home_page.png",
    "/projects/jobsdublin/just_pagination_pages.png",
    "/projects/jobsdublin/search_jobs.png",
    "/projects/jobsdublin/sign_in_via_google.png",
    "/projects/jobsdublin/user_apply_cv.png",
    "/projects/jobsdublin/user_apply_noCV_DandD_zone.png"
  ],
  "diploma": [
    "/projects/diploma/main.png",
    "/projects/diploma/login.png",
    "/projects/diploma/chat.png",
    "/projects/diploma/cart.png",
    "/projects/diploma/add.png",
    "/projects/diploma/profile.png",
    "/projects/diploma/order.png",
    "/projects/diploma/category.png",
    "/projects/diploma/Account.png",
    "/projects/diploma/Advertisement.png",
    "/projects/diploma/Carts.png",
    "/projects/diploma/Categories.png",
    "/projects/diploma/Orders.png",
  ],
  "crocodile": [
    "/projects/crocodile/chat-drawing.png",
    "/projects/crocodile/login.png",
  ],
  "memory": [
    "/projects/memory/cards.png",
    "/projects/memory/last.png",
    "/projects/memory/main.png",
  ],
  "collegeReception": [
    "/projects/collegeReception/main.png",
    "/projects/collegeReception/info.png",
    "/projects/collegeReception/add.png",
  ],
  "castle": [
    "/projects/castle/main.png",
    "/projects/castle/shoot.png",
  ],
  "applePicker": [
    "/projects/applePicker/main.png",
  ],
  "shopAndroid": [
    "/projects/shopAndroid/main.png",
    "/projects/shopAndroid/add.png",
    "/projects/shopAndroid/login.png",
    "/projects/shopAndroid/api.png",
  ]
};